name: fb_core
description: "Featurebase core package"
version: 0.0.1
homepage: https://github.com/ae1dev/fb_core

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.7.0
  freezed: ^2.5.7
  source_gen: ^1.5.0
  json_serializable: ^6.8.0
  flutter_gen: ^5.8.0
  copy_with_extension_gen: ^6.0.0
